site:
  title: Tech Write Me
  start_page: documentation:ROOT:index.adoc
#  url: /en
runtime:
  fetch: true
content:
  sources:
    - url: https://github.com/antontuhai/techwriteme
      branches: ["master"]
      start_path: docs

output:
  clean: true
  dir: ./output

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
#    - asciidoctor-plantuml
    - ./supplemental-ui/extensions/swagger.extension
#    - '@asciidoctor/tabs'
#    - asciidoctor-kroki