openapi: 3.0.0
info:
  title: AppleTransfer API
  version: 1.0.0
  description: API for sending apples between systems.
servers:
  - url: https://api.appletransfer.com/v1
paths:
  /send:
    post:
      summary: Send Apples
      description: Send apples to a specified system.
      operationId: sendApples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppleSendRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppleSendResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /status/{transactionId}:
    get:
      summary: Check Status
      description: Retrieve the status of a specific apple transfer.
      operationId: checkStatus
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppleStatusResponse'
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AppleSendRequest:
      type: object
      properties:
        recipientSystem:
          type: string
        quantity:
          type: integer
        variety:
          type: string
    AppleSendResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
    AppleStatusResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
        timestamp:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        error:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
