openapi: 3.0.0
info:
  title: AppleTransfer API
  version: 1.0.0
  description: This API allows for sending apples between systems, checking the status of these transactions, cancelling transfers, and updating transfer details.

servers:
  - url: https://api.appletransfer.com/v1

paths:
  /send:
    post:
      summary: Send apples
      description: Initiates the transfer of apples to a specified recipient system.
      operationId: sendApples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendApplesRequest'
      responses:
        '200':
          description: Successfully sent apples.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendApplesResponse'

  /status/{transactionId}:
    get:
      summary: Check status
      description: Retrieves the current status of an apple transfer using the transaction ID.
      operationId: checkStatus
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved transaction status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckStatusResponse'

  /cancel/{transactionId}:
    post:
      summary: Cancel transfer
      description: Cancels an ongoing apple transfer.
      operationId: cancelTransfer
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transfer cancelled successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelTransferResponse'

  /update/{transactionId}:
    put:
      summary: Update transfer
      description: Modifies the details of an existing apple transfer.
      operationId: updateTransfer
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransferRequest'
      responses:
        '200':
          description: Transfer updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTransferResponse'

components:
  schemas:
    SendApplesRequest:
      type: object
      required:
        - recipientSystem
        - quantity
        - variety
      properties:
        recipientSystem:
          type: string
          description: The unique identifier of the recipient system.
        quantity:
          type: integer
          description: The number of apples to send.
        variety:
          type: string
          description: The variety of apple (e.g., 'Gala', 'Fuji').

    SendApplesResponse:
      type: object
      properties:
        transactionId:
          type: string
          description: A unique identifier for the transaction.
        status:
          type: string
          description: The status of the transaction (e.g., 'sent').

    CheckStatusResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
          description: The current status of the transfer (e.g., 'in transit').
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the latest status update.

    CancelTransferResponse:
      type: object
      properties:
        message:
          type: string
          description: Confirmation message of the cancellation.

    UpdateTransferRequest:
      type: object
      properties:
        quantity:
          type: integer
          description: (Optional) The new number of apples to send.
        variety:
          type: string
          description: (Optional) The new variety of apple.

    UpdateTransferResponse:
      type: object
      properties:
        message:
          type: string
          description: Confirmation message of the update.

    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error encountered.

securitySchemes:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization

security:
  - ApiKeyAuth: []